import Foundation

// MARK: - Localization

enum AppLanguage: String, CaseIterable, Codable {
    case en = "en"
    case zhHans = "zh-Hans"
    case zhHant = "zh-Hant"
    case ja = "ja"

    var displayName: String {
        switch self {
        case .en:     return "EN"
        case .zhHans: return "简"
        case .zhHant: return "繁"
        case .ja:     return "JP"
        }
    }

    static func fromSystem() -> AppLanguage {
        let lang = Locale.preferredLanguages.first ?? "en"
        if lang.hasPrefix("zh-Hans") || lang.hasPrefix("zh-CN") { return .zhHans }
        if lang.hasPrefix("zh-Hant") || lang.hasPrefix("zh-TW") || lang.hasPrefix("zh-HK") { return .zhHant }
        if lang.hasPrefix("zh") { return .zhHans }  // bare "zh" → Simplified
        if lang.hasPrefix("ja") { return .ja }
        return .en
    }
}

/// Value-type localizer. Captures the active language so the value is Equatable —
/// injected through the SwiftUI environment, a language switch produces a different
/// value and SwiftUI re-renders every view that reads it. Resolution order matches
/// the store's lookup exactly: active language → English → raw key.
struct Localizer: Equatable {
    var language: AppLanguage

    func callAsFunction(_ key: String) -> String {
        i18n[language]?[key] ?? i18n[.en]?[key] ?? key
    }
}

let i18n: [AppLanguage: [String: String]] = [
    .en: [
        "tkIn":         "in",
        "tkOut":        "out",
        "tkCR":         "c_r",
        "tkCW":         "c_w",
        "title":        "Local CC Usage",
        "cost":         "Cost",
        "tokens":       "Tokens",
        "today":        "Today",
        "thisWeek":     "This Week",
        "thisMonth":    "This Month",
        "monthlyTotal": "Monthly Total",
        "daily":        "Daily",
        "noData":       "No data",
        "loading":      "Loading usage data…",
        "loadFailed":   "Failed to load data",
        "noMonthData":  "No data for this month",
        "updated":      "Updated %@",
        "cachedData":   "Cached data",
        "refresh":      "Refresh (⌘R)",
        "quit":         "Quit",
        "justNow":      "just now",
        "mAgo":         "%dm ago",
        "hAgo":         "%dh ago",
        "dAgo":         "%dd ago",
        "mTokens":      "%.1fm tokens",
        "kTokens":      "%.1fk tokens",
        "nTokens":      "%d tokens",
        "win5hHeader":       "5-hour window",
        "win5hResetsIn":     "Resets in %@",
        "win5hLocal":        "Local this window",
        "win5hQuotaSection": "Subscription quota",
        "win5hMsgs":         "msgs",
        "quota5h":           "5h",
        "quota7d":           "7d",
        "quota7dSonnet":     "7d · Sonnet",
        "quotaWarnHigh":     "⏰ Close to limit",
        "quotaExtra":        "💸 Extra usage on",
        "quotaFetchFail":    "Quota API failed",
        "quotaTokenExpired": "Token expired — run `claude login`",
        "quotaRateLimited":  "Rate limited — retrying soon",
        "quotaDecodeFail":   "Unexpected response schema",
        "bedrockNote":       "API-key auth — no subscription 5h/weekly quota applies.",
        "subTab":            "Plan",
        "subTitle":          "Remaining quota",
        "subRemaining":      "%@ left",
        "subUsedFmt":        "%d%% used",
        "subResetFmt":       "resets in %@",
        "sub5hLabel":        "5-hour window",
        "sub7dLabel":        "7-day · all models",
        "sub7dSonnetLabel":  "7-day · Sonnet",
        "subWaitData":       "Loading quota…",
        "subNoToken":        "No subscription detected. API-key users (Bedrock / Vertex / Console) have no 5h / weekly cap.",
        "subExtraOn":        "Extra usage enabled — overage billed beyond plan limits.",
        "timeTab":           "Time",
        "timeWeek":          "Week",
        "timeMonth":         "Month",
        "timeYear":          "Year",
        "timeWeekTotal":     "Week total",
        "timeDailyAvg":      "Daily avg",
        "timeLongest":       "Longest",
        "timeLess":          "Less",
        "timeMore":          "More",
        "timeLoadingYear":   "Loading year…",
    ],
    .zhHans: [
        "tkIn":         "输入",
        "tkOut":        "输出",
        "tkCR":         "缓读",
        "tkCW":         "缓写",
        "title":        "CC 用量监控",
        "cost":         "费用",
        "tokens":       "Tokens",
        "today":        "今日",
        "thisWeek":     "本周",
        "thisMonth":    "本月",
        "monthlyTotal": "月度汇总",
        "daily":        "每日",
        "noData":       "无数据",
        "loading":      "加载用量数据…",
        "loadFailed":   "数据加载失败",
        "noMonthData":  "当月无数据",
        "updated":      "%@ 更新",
        "cachedData":   "缓存数据",
        "refresh":      "刷新 (⌘R)",
        "quit":         "退出",
        "justNow":      "刚刚",
        "mAgo":         "%d分钟前",
        "hAgo":         "%d小时前",
        "dAgo":         "%d天前",
        "mTokens":      "%.1fm tokens",
        "kTokens":      "%.1fk tokens",
        "nTokens":      "%d tokens",
        "win5hHeader":       "5 小时窗口",
        "win5hResetsIn":     "%@ 后重置",
        "win5hLocal":        "本窗口本机消耗",
        "win5hQuotaSection": "订阅配额",
        "win5hMsgs":         "条",
        "quota5h":           "5小时",
        "quota7d":           "7天",
        "quota7dSonnet":     "7天 · Sonnet",
        "quotaWarnHigh":     "⏰ 接近上限",
        "quotaExtra":        "💸 已开启额外用量",
        "quotaFetchFail":    "订阅配额 API 失败",
        "quotaTokenExpired": "Token 过期,请运行 `claude login`",
        "quotaRateLimited":  "被限流了,稍后重试",
        "quotaDecodeFail":   "响应格式异常",
        "bedrockNote":       "API key 鉴权 — 不受订阅的 5h/周限额约束",
        "subTab":            "订阅",
        "subTitle":          "剩余用量",
        "subRemaining":      "剩余 %@",
        "subUsedFmt":        "已用 %d%%",
        "subResetFmt":       "%@ 后重置",
        "sub5hLabel":        "5 小时窗口",
        "sub7dLabel":        "7 天 · 全部模型",
        "sub7dSonnetLabel":  "7 天 · Sonnet",
        "subWaitData":       "正在获取配额…",
        "subNoToken":        "未检测到订阅。API-key 用户（Bedrock / Vertex / Console）没有 5 小时 / 每周限额。",
        "subExtraOn":        "已开启额外用量 — 超出套餐部分将另行计费。",
        "timeTab":           "时长",
        "timeWeek":          "周",
        "timeMonth":         "月",
        "timeYear":          "年",
        "timeWeekTotal":     "本周合计",
        "timeDailyAvg":      "日均",
        "timeLongest":       "最长连续",
        "timeLess":          "少",
        "timeMore":          "多",
        "timeLoadingYear":   "加载年度数据…",
    ],
    .zhHant: [
        "tkIn":         "輸入",
        "tkOut":        "輸出",
        "tkCR":         "緩讀",
        "tkCW":         "緩寫",
        "title":        "CC 用量監控",
        "cost":         "費用",
        "tokens":       "Tokens",
        "today":        "今日",
        "thisWeek":     "本週",
        "thisMonth":    "本月",
        "monthlyTotal": "月度匯總",
        "daily":        "每日",
        "noData":       "無數據",
        "loading":      "載入用量數據…",
        "loadFailed":   "數據載入失敗",
        "noMonthData":  "當月無數據",
        "updated":      "%@ 更新",
        "cachedData":   "快取數據",
        "refresh":      "重新整理 (⌘R)",
        "quit":         "結束",
        "justNow":      "剛剛",
        "mAgo":         "%d分鐘前",
        "hAgo":         "%d小時前",
        "dAgo":         "%d天前",
        "mTokens":      "%.1fm tokens",
        "kTokens":      "%.1fk tokens",
        "nTokens":      "%d tokens",
        "win5hHeader":       "5 小時視窗",
        "win5hResetsIn":     "%@ 後重置",
        "win5hLocal":        "本視窗本機消耗",
        "win5hQuotaSection": "訂閱配額",
        "win5hMsgs":         "條",
        "quota5h":           "5小時",
        "quota7d":           "7天",
        "quota7dSonnet":     "7天 · Sonnet",
        "quotaWarnHigh":     "⏰ 接近上限",
        "quotaExtra":        "💸 已啟用額外用量",
        "quotaFetchFail":    "訂閱配額 API 失敗",
        "quotaTokenExpired": "Token 過期,請執行 `claude login`",
        "quotaRateLimited":  "被限流了,稍後重試",
        "quotaDecodeFail":   "回應格式異常",
        "bedrockNote":       "API key 驗證 — 不受訂閱的 5h/週限額約束",
        "subTab":            "訂閱",
        "subTitle":          "剩餘用量",
        "subRemaining":      "剩餘 %@",
        "subUsedFmt":        "已用 %d%%",
        "subResetFmt":       "%@ 後重置",
        "sub5hLabel":        "5 小時視窗",
        "sub7dLabel":        "7 天 · 全部模型",
        "sub7dSonnetLabel":  "7 天 · Sonnet",
        "subWaitData":       "正在取得配額…",
        "subNoToken":        "未偵測到訂閱。API-key 使用者（Bedrock / Vertex / Console）沒有 5 小時 / 每週限額。",
        "subExtraOn":        "已啟用額外用量 — 超出方案部分將另行計費。",
        "timeTab":           "時長",
        "timeWeek":          "週",
        "timeMonth":         "月",
        "timeYear":          "年",
        "timeWeekTotal":     "本週合計",
        "timeDailyAvg":      "日均",
        "timeLongest":       "最長連續",
        "timeLess":          "少",
        "timeMore":          "多",
        "timeLoadingYear":   "載入年度數據…",
    ],
    .ja: [
        "tkIn":         "入力",
        "tkOut":        "出力",
        "tkCR":         "c読",
        "tkCW":         "c書",
        "title":        "CC 使用量",
        "cost":         "コスト",
        "tokens":       "トークン",
        "today":        "今日",
        "thisWeek":     "今週",
        "thisMonth":    "今月",
        "monthlyTotal": "月間合計",
        "daily":        "日別",
        "noData":       "データなし",
        "loading":      "使用量を読み込み中…",
        "loadFailed":   "データの読み込みに失敗",
        "noMonthData":  "今月のデータなし",
        "updated":      "%@ に更新",
        "cachedData":   "キャッシュデータ",
        "refresh":      "更新 (⌘R)",
        "quit":         "終了",
        "justNow":      "たった今",
        "mAgo":         "%d分前",
        "hAgo":         "%d時間前",
        "dAgo":         "%d日前",
        "mTokens":      "%.1fm トークン",
        "kTokens":      "%.1fk トークン",
        "nTokens":      "%d トークン",
        "win5hHeader":       "5 時間ウィンドウ",
        "win5hResetsIn":     "%@後にリセット",
        "win5hLocal":        "このウィンドウの消費",
        "win5hQuotaSection": "サブスク配分",
        "win5hMsgs":         "件",
        "quota5h":           "5h",
        "quota7d":           "7d",
        "quota7dSonnet":     "7d · Sonnet",
        "quotaWarnHigh":     "⏰ 上限間近",
        "quotaExtra":        "💸 追加利用が有効",
        "quotaFetchFail":    "配分 API 失敗",
        "quotaTokenExpired": "Token 期限切れ — `claude login` を実行",
        "quotaRateLimited":  "レート制限中 — 後ほど再試行",
        "quotaDecodeFail":   "予期しない応答形式",
        "bedrockNote":       "API キー認証 — サブスクの 5h/週の制限は適用されません",
        "subTab":            "プラン",
        "subTitle":          "残りクォータ",
        "subRemaining":      "残り %@",
        "subUsedFmt":        "%d%% 使用",
        "subResetFmt":       "%@後にリセット",
        "sub5hLabel":        "5 時間ウィンドウ",
        "sub7dLabel":        "7 日間 · 全モデル",
        "sub7dSonnetLabel":  "7 日間 · Sonnet",
        "subWaitData":       "クォータを取得中…",
        "subNoToken":        "サブスクが検出されません。API キー（Bedrock / Vertex / Console）には 5h / 週の上限はありません。",
        "subExtraOn":        "追加利用が有効 — プラン上限を超過分は別途課金されます。",
        "timeTab":           "時間",
        "timeWeek":          "週",
        "timeMonth":         "月",
        "timeYear":          "年",
        "timeWeekTotal":     "週合計",
        "timeDailyAvg":      "日平均",
        "timeLongest":       "最長",
        "timeLess":          "少",
        "timeMore":          "多",
        "timeLoadingYear":   "年間データを読み込み中…",
    ],
]
